# espanso match file
matches:
  # Print the current date
  - trigger: ";date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y%m%d"

  - trigger: ";ddate"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d.%m.%Y"

  # Print the output of a shell command
  - trigger: ";shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"

  # Simple text replacement
  - trigger: ";br"
    replace: "Best regards,\n\nIgor Cervenka"

  - trigger: ";p"
    replace: "proj"

  - trigger: ";obsbox"
    replace: "> [!Note]\n"
    label: "Note"
  - trigger: ";obsbox"
    replace: "> [!Info]\n"
    label: "Info"
  - trigger: ";obsbox"
    replace: "> [!Todo]\n"
    label: "Todo"
  - trigger: ";obsbox"
    replace: "> [!Tip]\n"
    label: "Tip"
  - trigger: ";obsbox"
    replace: "> [!Quote]\n"
    label: "Quote"
  - trigger: ";obsbox"
    replace: "> [!Example]\n"
    label: "Example"
  - trigger: ";obsbox"
    replace: "> [!Abstract]\n"
    label: "Abstract"
  - trigger: ";obsbox"
    replace: "> [!Question]\n"
    label: "Question"
  - trigger: ";obsbox"
    replace: "> [!Success]\n"
    label: "Success"
  - trigger: ";obsbox"
    replace: "> [!Warning]\n"
    label: "Warning"
  - trigger: ";obsbox"
    replace: "> [!Failure]\n"
    label: "Failure"
  - trigger: ";obsbox"
    replace: "> [!Bug]\n"
    label: "Bug"

  - trigger: ";obstodo"
    replace: "## <mark style='background: #BBFABBA6;'> ToDo</mark>"

  - trigger: ";rch"
    replace: "```{r }\n\n```\n"

  - trigger: ";cdmartiniv"
    replace: "/scicore/home/martiniv/GROUP/bioinfo"

  - trigger: ";cdivanek"
    replace: "/scicore/home/ivanek/GROUP/"

  - trigger: ";cdhome"
    replace: "/scicore/home/ivanek/cerven0000/"

  - trigger: ";irobert"
    replace: "Robert Ivanek (robert.ivanek@unibas.ch)"

  - trigger: ";ianastasiya"
    replace: "Anastasiya Börsch (anastasiya.boersch@unibas.ch)"

  - trigger: ";idominik"
    replace: "Dominik Burri (dominik.burri@unibas.ch)"

  - trigger: ";iigor"
    replace: "Igor Cervenka (igor.cervenka@unibas.ch)"

  - trigger: ";iathimed"
    replace: "Athimed El Taher (athimed.eltaher@unibas.ch)"

  - trigger: ";ijulien"
    replace: "Julien Roux (julien.roux@unibas.ch)"

  - trigger: ";iflorian"
    replace: "Florian Geier (florian.geier@unibas.ch)"

  - trigger: ";snakemake_cluster"
    replace: "snakemake --use-conda --profile scicore-slurm -p --rerun-incomplete --conda-prefix ~/snakemake_environments"

  - trigger: ";snakemake_envs"
    replace: "snakemake  --conda-create-envs-only --use-conda --conda-prefix ~/snakemake_environments"
