# espanso match file
matches:
  # Print the current date
  - trigger: ";date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y%m%d"

  # Print the output of a shell command
  - trigger: ";shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"

  # Simple text replacement
  - trigger: ";br"
    replace: "Best regards,\n\nIgor Cervenka"

  - trigger: ";p"
    replace: "proj"

  - trigger: ";obsbox"
    replace: "> [!Note]\n"
    label: "Note"
  - trigger: ";obsbox"
    replace: "> [!Info]\n"
    label: "Info"
  - trigger: ";obsbox"
    replace: "> [!Todo]\n"
    label: "Todo"
  - trigger: ";obsbox"
    replace: "> [!Tip]\n"
    label: "Tip"
  - trigger: ";obsbox"
    replace: "> [!Quote]\n"
    label: "Quote"
  - trigger: ";obsbox"
    replace: "> [!Example]\n"
    label: "Example"
  - trigger: ";obsbox"
    replace: "> [!Abstract]\n"
    label: "Abstract"
  - trigger: ";obsbox"
    replace: "> [!Question]\n"
    label: "Question"
  - trigger: ";obsbox"
    replace: "> [!Success]\n"
    label: "Success"
  - trigger: ";obsbox"
    replace: "> [!Warning]\n"
    label: "Warning"
  - trigger: ";obsbox"
    replace: "> [!Failure]\n"
    label: "Failure"
  - trigger: ";obsbox"
    replace: "> [!Bug]\n"
    label: "Bug"

  - trigger: ";obstodo"
    replace: "## <mark style='background: #BBFABBA6;'> ToDo</mark>"

  # And much more! For more information, visit the docs: https://espanso.org/docs/
  #
